name: CI
on:
    push
jobs: 
    run-tests:
        runs-on: ubuntu-latest
        
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependecies
              run: npm i

            - name: Run tests
              run: npm test
